// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelMemories.Database;

#nullable disable

namespace TravelMemories.Migrations
{
    [DbContext(typeof(ImageMetadataDBContext))]
    [Migration("20260211185053_add oauth flow 1")]
    partial class addoauthflow1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ChatConversation", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConversationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ConversationId");

                    b.HasIndex("UserEmail");

                    b.ToTable("ChatbotConversations", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ChatMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MessageRole")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ChatMessages", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ImageMetadata", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedByEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("X")
                        .HasColumnType("real");

                    b.Property<float>("Y")
                        .HasColumnType("real");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UploadedByEmail");

                    b.ToTable("ImageMetadata", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.OAuthCodeStore", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LoginChallenge")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("OAuthCodeStores", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.SubscriptionDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("PlanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlanType")
                        .HasColumnType("int");

                    b.Property<float>("StorageCapacityInGB")
                        .HasColumnType("real");

                    b.Property<float>("StorageUsedInGB")
                        .HasColumnType("real");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("SubscriptionDetails", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.UserInfo", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsManualLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("ProfilePictureURL")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UserInfo", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.VerificationCodes", b =>
                {
                    b.Property<string>("UserEmail")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("OTP")
                        .HasColumnType("int");

                    b.HasKey("UserEmail");

                    b.ToTable("VerificationCodes", (string)null);
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ChatConversation", b =>
                {
                    b.HasOne("TravelMemoriesBackend.Contracts.Data.UserInfo", "UserInfo")
                        .WithMany("ChatConversations")
                        .HasForeignKey("UserEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserInfo");
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ChatMessage", b =>
                {
                    b.HasOne("TravelMemoriesBackend.Contracts.Data.ChatConversation", "ChatConversation")
                        .WithMany("ConversationMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatConversation");
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ImageMetadata", b =>
                {
                    b.HasOne("TravelMemoriesBackend.Contracts.Data.UserInfo", "UploadedBy")
                        .WithMany("Images")
                        .HasForeignKey("UploadedByEmail")
                        .HasPrincipalKey("Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.SubscriptionDetails", b =>
                {
                    b.HasOne("TravelMemoriesBackend.Contracts.Data.UserInfo", "User")
                        .WithOne("SubscriptionDetails")
                        .HasForeignKey("TravelMemoriesBackend.Contracts.Data.SubscriptionDetails", "UserEmail")
                        .HasPrincipalKey("TravelMemoriesBackend.Contracts.Data.UserInfo", "Email")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.ChatConversation", b =>
                {
                    b.Navigation("ConversationMessages");
                });

            modelBuilder.Entity("TravelMemoriesBackend.Contracts.Data.UserInfo", b =>
                {
                    b.Navigation("ChatConversations");

                    b.Navigation("Images");

                    b.Navigation("SubscriptionDetails")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
